on:
  pull_request:

jobs:
  # build_docker_image:
  #   name: "Call build and push action"
  #   uses: ./.github/workflows/build-and-push-Docker-image.yml
  #   secrets: inherit
  #   with:
  #     image-name: workflow.transition.monitor
  #     image-tag: pr${{ github.event.pull_request.number }}

  build_private_docker_image:
    name: "Build private docker image"
    uses: ./.github/workflows/build-push-private.yml
    secrets: inherit
    with:
      image-name: gh-actions-test

  # add_comment:
  #   needs: build_docker_image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Find Comment
  #       # https://github.com/peter-evans/find-comment
  #       uses: peter-evans/find-comment@v3
  #       id: fc
  #       with:
  #         issue-number: ${{ github.event.pull_request.number }}
  #         comment-author: 'github-actions[bot]'
  #         body-includes: Docker image from this PR

      # - name: Create or update comment
      #   # https://github.com/peter-evans/create-or-update-comment
      #   uses: peter-evans/create-or-update-comment@v4
      #   with:
      #     comment-id: ${{ steps.fc.outputs.comment-id }}
      #     issue-number: ${{ github.event.pull_request.number }}
      #     body: |
      #       Docker image from this PR (${{ github.event.pull_request.head.sha }}) created
      #       ```
      #       docker pull ${{ needs.build_docker_image.outputs.full-image-name }}
      #       ```
      #     edit-mode: replace
