on:
  workflow_call:
    inputs:
      image-name:
        required: false
        default: rmi_pacta_2023q4_pa2024ch
        type: string
      image-tag:
        required: true
        type: string
      push-latest:
        required: false
        type: boolean
        description: Push the `latest` tag in addition to the timestamp tag?
        default: false

    outputs:
      full-image-name:
        description: "Full pushed image name including host/registry, name, and tag"
        value: ${{ jobs.docker-build.outputs.full-image-name }}
jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 90
    outputs:
      full-image-name: ${{ steps.push-image.outputs.full-image-name }}

    steps:
      - name: Set current date as env variable
        run: |
          NOW="$(date -u +'%Y%m%dT%H%M%SZ')"
          echo "NOW=$NOW" >> $GITHUB_ENV
          echo "$NOW"

      - name: Checkout workflow.transition.monitor
        uses: actions/checkout@v4
        with:
          path: workflow.transition.monitor

      - name: Checkout templates.transition.monitor
        uses: actions/checkout@v4
        with:
          repository: RMI-PACTA/templates.transition.monitor
          path: templates.transition.monitor
          token: ${{ secrets.TEMPLATES_TOKEN }}

      # https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-azure-cli-script-of-a-specific-cli-version
      - name: Download pacta-data
        uses: azure/CLI@v1
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            pacta_data_share_url="https://pactadatadev.file.core.windows.net/workflow-data-preparation-outputs"
            pacta_data_share_path="2023Q4_20240218T231047Z"
            az version
            az account show
            az storage copy \
              --source "$pacta_data_share_url"/"$pacta_data_share_path" \
              --destination "pacta-data" \
              --recursive \
              --exclude-pattern "*.sqlite"
            mv pacta-data/$pacta_data_share_path pacta-data/2023Q4
            ls pacta-data/2023Q4

      - name: Build Docker image
        run: |
          cp workflow.transition.monitor/Dockerfile Dockerfile
          docker build . --file Dockerfile --tag "transitionmonitordockerregistry.azurecr.io/${{ inputs.image-name }}:$NOW"

      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-masking-a-generated-output-within-a-single-job
      - name: Get credentials for docker registry
        uses: azure/CLI@v1
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            # Username is not a placeholder. See https://stackoverflow.com/a/73250630
            DOCKER_USER="00000000-0000-0000-0000-000000000000" >> "$GITHUB_ENV"
            DOCKER_TOKEN="$(az acr login -n transitionmonitordockerregistry --expose-token --query 'accessToken' --output tsv)" >> "$GITHUB_ENV"
            # echo "::add-mask::$DOCKER_USER"
            echo "::add-mask::$DOCKER_TOKEN"
            echo "DOCKER_USER=$DOCKER_USER" >> "$GITHUB_ENV"
            echo "DOCKER_TOKEN=$DOCKER_TOKEN" >> "$GITHUB_ENV"

      - name: Login and Push Docker image
        run: |
          docker login transitionmonitordockerregistry.azurecr.io -u "$DOCKER_USER" -p "$DOCKER_TOKEN"
          docker push "transitionmonitordockerregistry.azurecr.io/${{ inputs.image-name }}:$NOW"

      - name: Push Docker `latest` tag
        if: ${{ inputs.push-latest }}
        run: |
          docker tag "transitionmonitordockerregistry.azurecr.io/${{ inputs.image-name }}:$NOW" "transitionmonitordockerregistry.azurecr.io/${{ inputs.image-name }}:latest"
          docker push "transitionmonitordockerregistry.azurecr.io/${{ inputs.image-name }}:latest"
