name: Docker build & test

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1,2,3,4,5'
  workflow_dispatch:

jobs:

  build_private_docker_image:
    name: "Test File upload"
    needs: build_docker_image
    uses: ./.github/workflows/build-push-private.yml
    secrets: inherit
