on:
  workflow_call:
    inputs:
      image-name:
        required: false
        default: rmi_pacta_2023q4_pa2024ch
        type: string
      image-tag:
        required: true
        type: string
    outputs:
      full-image-name:
        description: "Full pushed image name including host/registry, name, and tag"
        value: ${{ jobs.docker-build.outputs.full-image-name }}
jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 90
    outputs:
      full-image-name: ${{ steps.push-image.outputs.full-image-name }}

    steps:

      - name: Checkout workflow.transition.monitor
        uses: actions/checkout@v3
        with:
          path: workflow.transition.monitor

      - name: Checkout templates.transition.monitor
        uses: actions/checkout@v3
        with:
          repository: RMI-PACTA/templates.transition.monitor
          path: templates.transition.monitor
          token: ${{ secrets.REPO_PAT }}

      # https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-azure-cli-script-of-a-specific-cli-version
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            pacta_data_share_url="https://pactadatadev.file.core.windows.net/workflow-data-preparation-outputs"
            pacta_data_share_path="2023Q4_20240218T231047Z"
            az version
            az account show
            az storage copy -s "$pacta_data_share_url"/"$pacta_data_share_path"  -d "pacta-data" --recursive --exclude-pattern "*.sqlite"
            mv pacta-data/$pacta_data_share_path pacta-data/2023Q4
            ls pacta-data/2023Q4

      - name: Build Docker image
        run: |
          cp workflow.transition.monitor/Dockerfile Dockerfile
          docker build . --file Dockerfile --tag "transitionmonitordockerregistry.azurecr.io/${{ inputs.image-name }}:${{ github.event.repository.updated_at}}"

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            az acr login -n transitionmonitordockerregistry

      - name: Build Docker image
        run: |
          docker push "transitionmonitordockerregistry.azurecr.io/${{ inputs.image-name }}:${{ github.event.repository.updated_at}}"
          docker tag "transitionmonitordockerregistry.azurecr.io/${{ inputs.image-name }}:${{ github.event.repository.updated_at}}" "transitionmonitordockerregistry.azurecr.io/${{ inputs.image-name }}:latest"
          docker push "transitionmonitordockerregistry.azurecr.io/${{ inputs.image-name }}:latest"
