on:
  workflow_call:

jobs:
  test-upload:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:

      - name: Prepare Test files
        run: |
          mkdir test_dir
          echo "foo" > test_dir/test.txt
          echo "bar" > test_dir/test2.txt

      - name: Upload results to blob store using az
        id: upload-directory
        uses: RMI-PACTA/actions/actions/azure/azcopy-copy@azcopy-actions
        with:
          source: 'test_dir/'
          destination: https://pactadatadev.blob.core.windows.net/ghactions-workflow-transition-monitor-results-reports/alpha/path/to/file
          flags: |
            --recursive

      - name: Download results to blob store using az
        id: upload-directory
        uses: RMI-PACTA/actions/actions/azure/azcopy-copy@azcopy-actions
        with:
          destination: 'foo/'
          source: https://pactadatadev.blob.core.windows.net/ghactions-workflow-transition-monitor-results-reports/alpha/
          flags: |
            --recursive
