on:
  workflow_call:

jobs:
  test-upload:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:

      - name: Prepare Test files
        run: |
          mkdir test_dir
          echo "foo" > test_dir/test.txt
          echo "bar" > test_dir/test2.txt

      - name: Install `azcopy`
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sSL -O https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y azcopy

          # Show version
          echo "azcopy version:"
          azcopy --version
          # Show path
          echo "azcopy path:"
          type azcopy

      # https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-azure-cli-script-of-a-specific-cli-version
      - name: Upload results to blob store
        env:
          AZCOPY_AUTO_LOGIN_TYPE: AZCLI
          AZCOPY_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        uses: azure/CLI@v2
        with:
          inlineScript: |

            echo "Running azcopy"
            /usr/local/bin/azcopy \
            copy \
            test_dir \
            https://pactadatadev.dfs.core.windows.net/ghactions-workflow-transition-monitor-results-reports/foo \
            --recursive

            echo "running az storage fs"
            az storage fs directory upload \
              --source "test_dir" \
              --file-system "ghactions-workflow-transition-monitor-results-reports" \
              --account-name "pactadatadev" \
              --auth-mode "login" \
              --recursive
