on:
  push:
    branches: [main]

jobs:
  build_docker_image:
    name: "Call build and push action"
    uses: ./.github/workflows/build-and-push-Docker-image.yml
    secrets: inherit
    with:
      image-name: workflow.transition.monitor
      image-tag: main
