on:
  schedule:
    - cron:  '0 0 * * 1,2,3,4,5'

env:
  IMAGE_NAME: workflow.transition.monitor

jobs:
  Docker-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    timeout-minutes: 25

    steps:
      - name: Checkout workflow.transition.monitor
        uses: actions/checkout@v3
        with:
          path: workflow.transition.monitor

      - name: Checkout pacta.portfolio.import
        uses: actions/checkout@v3
        with:
          repository: RMI-PACTA/pacta.portfolio.import
          token: ${{ secrets.GITHUB_TOKEN }}
          path: pacta.portfolio.import

      - name: Checkout pacta.portfolio.allocate
        uses: actions/checkout@v3
        with:
          repository: RMI-PACTA/pacta.portfolio.allocate
          token: ${{ secrets.PAT_ADD_ISSUES_TO_PROJECT }}
          path: pacta.portfolio.allocate

      - name: Checkout pacta.portfolio.audit
        uses: actions/checkout@v3
        with:
          repository: RMI-PACTA/pacta.portfolio.audit
          token: ${{ secrets.GITHUB_TOKEN }}
          path: pacta.portfolio.audit

      - name: Checkout pacta.portfolio.utils
        uses: actions/checkout@v3
        with:
          repository: RMI-PACTA/pacta.portfolio.utils
          token: ${{ secrets.GITHUB_TOKEN }}
          path: pacta.portfolio.utils

      - name: Checkout pacta.portfolio.report
        uses: actions/checkout@v3
        with:
          repository: RMI-PACTA/pacta.portfolio.report
          token: ${{ secrets.GITHUB_TOKEN }}
          path: pacta.portfolio.report

      - name: Checkout pacta.executive.summary
        uses: actions/checkout@v3
        with:
          repository: RMI-PACTA/pacta.executive.summary
          token: ${{ secrets.GITHUB_TOKEN }}
          path: pacta.executive.summary

      - name: Checkout templates.transition.monitor
        uses: actions/checkout@v3
        with:
          repository: RMI-PACTA/templates.transition.monitor
          token: ${{ secrets.PAT_ADD_ISSUES_TO_PROJECT }}
          path: templates.transition.monitor

      - name: Make fake (empty) pacta-data folder
        run: mkdir pacta-data

      - name: Build Docker image
        run: |
          cp workflow.transition.monitor/Dockerfile Dockerfile
          docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        id: push-image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Use Docker `nightly` tag convention
          VERSION=nightly
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          echo "BUILD_NAME_TAG=$IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT
